[package]
name = "war3parser-cli"
version.workspace = true
edition.workspace = true
description = "Command line extractor and parser for Warcraft 3 map files"
documentation = "https://docs.rs/war3parser"
homepage.workspace = true
repository.workspace = true
keywords = ["warcraft3", "MPQ", "parser"]
categories = ["command-line-utilities"]
license.workspace = true
readme = "../war3parser/README.md"

[dependencies]
war3parser = { workspace = true, features = ["serde"] }
clap = { version = "4.5.9", features = ["derive"] }
anyhow = "1.0.95"
