[package]
name = "war3parser-wasm"
version.workspace = true
edition.workspace = true
description = "WebAssembly bindings for the war3parser Warcraft 3 map parser"
documentation = "https://docs.rs/war3parser"
homepage.workspace = true
repository.workspace = true
keywords = ["warcraft3", "MPQ", "parser"]
categories = ["wasm"]
license.workspace = true
readme = "../../docs/PARSER.md"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[dependencies]
js-sys = "0.3.77"
serde = { workspace = true }
serde-wasm-bindgen = { workspace = true }
war3parser = { workspace = true, features = ["serde"] }
wasm-bindgen = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.50"
